version: '3.8'
services:
  database:
    image: mariadb:11.8
    container_name: mdb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "Password1234"
    volumes:
      - ./mariadb-data:/var/lib/mysql # Bind mount to a local directory
      # Or use a named volume:
      # - mariadb_volume:/var/lib/mysql

# Define named volumes here if using Option 2
# volumes:
#   mariadb_volume: